let suggestions = [
    'EDITORIAL JUVENTUD S.A.',
    'NINGBO DYNACO HYDRAULIC CO., LTD.',
    'FINOTEX',
    'TRAY',
    'HITACHI Reliable Solutions',
    'WENZHOU MODERN WESHARE INTERNATIONAL BUSINESS CO., LTD',
    'MANSONS Driving change',
    'LPR',
    'LC DESIGNS TRADING CO., LIMITED',
    'NEXGEN PACKAGING MEXICO',
];